### Back all games
GET http://localhost:5005/games

### Back a game by id
GET http://localhost:5005/games/8

### Create a new game and return the created game. Protected by validation, but not from empty fields inside the body*
POST http://localhost:5005/games
Content-Type: application/json

{
    "name": "The Legend of Zelda: Breath of the Wild",
    "genre": "Action-adventure",
    "price": 59.99,
    "releaseDate": "2017-03-03"
}

### Update a game by id. Protected by validation, but not from empty fields inside the body*
PUT http://localhost:5005/games/1
Content-Type: application/json

{
    "name": "The Legend of Zelda: Breath of the Wild",
    "genre": "Action-adventure",
    "price": 49.99,
    "releaseDate": "2017-03-03"
}

### Delete a game by id
DELETE http://localhost:5005/games/3